site_name: DogsbodyDocs
nav:
  - Home: index.md
  - About: about.md
  - Incidents:
    - FTP Incident:
      - RCA: incidents/ftp-rca-20260205.md
      - fail2ban setup: projects/fail2ban-setup.md
  - Projects: 
    - fail2ban setup: projects/fail2ban-setup.md
theme: readthedocs