site_name: DogsbodyDocs
nav:
  - Home: index.md
  - About: about.md
  - Docs:
  - Incidents:
    - FTP Incident:
      - FTP Incident RCA: FTP-RCA-20260205.md
  - Projects: 
    - fail2ban setup: fail2ban-setup.md
theme: readthedocs